let questions = [["Question 1: What religion(s) is/are most common in China?", "Islam", "Roman Catholicism", "Folk religions & Buddhism", 3],
["Question 2: What religion(s) is/are most common in Poland?", "Christianity", "Roman Catholicism", "Islam", 2],
["Question 3: What religion(s) is/are most common in Algeria?", "Islam", "Catholicism", "Christianity", 1],
["Question 4: What religion(s) is/are most common in Nepal?", "Folk religions & Buddhism", "Hinduism", "Roman Catholicism", 2],
["Question 5: What religion(s) is/are most common in Spain?", "Islam", "Catholicism", "Buddhism", 2],
["Question 6: What religion(s) is/are most common in Uganda?", "Catholicism", "Christianity", "Christianity", 3],
["Question 7: What religion(s) is/are most common in Turkey?", "Christianity", "Christianity", "Islam", 3],
["Question 8: What religion(s) is/are most common in Malaysia?", "Islam", "Hinduism", "Buddhism", 1],
["Question 9: What religion(s) is/are most common in Russia?", "Islam", "Russian Orthodoxy", "Catholicism", 2],
["Question 10: What religion(s) is/are most common in Yemen?", "Christianity, Islam, Indigenous Religions", "Islam", "Roman Catholicism", 2],
["Question 11: What religion(s) is/are most common in Japan?", "Roman Catholicism", "Shinto and Buddhism", "Buddhism", 2],
["Question 12: What religion(s) is/are most common in United Kingdom?", "Christianity", "Islam", "Catholicism", 1],
["Question 13: What religion(s) is/are most common in Uganda?", "Roman Catholicism", "Christianity", "Catholicism", 2],
["Question 14: What religion(s) is/are most common in Ukraine?", "Eastern Orthodoxy", "Christianity", "Roman Catholicism", 1],
["Question 15: What religion(s) is/are most common in United Kingdom?", "Islam", "Christianity", "Islam", 2],
["Question 16: What religion(s) is/are most common in Vietnam?", "Islam", "Islam", "Buddhism and Catholicism", 3],
["Question 17: What religion(s) is/are most common in Ghana?", "Christianity", "Christianity", "Irreligious", 1],
["Question 18: What religion(s) is/are most common in Algeria?", "Russian Orthodoxy", "Catholicism", "Islam", 3],
["Question 19: What religion(s) is/are most common in Nepal?", "Hinduism", "Catholicism", "Christianity", 1],
["Question 20: What religion(s) is/are most common in Sudan?", "Islam", "Christianity", "Islam", 3],
["Question 21: What religion(s) is/are most common in Russia?", "Islam", "Russian Orthodoxy", "Buddhism", 2],
["Question 22: What religion(s) is/are most common in Bangladesh?", "Islam", "Christianity", "Folk religions & Buddhism", 1],
["Question 23: What religion(s) is/are most common in South Africa?", "Buddhism and Catholicism", "Christianity", "Islam", 2],
["Question 24: What religion(s) is/are most common in Saudi Arabia?", "Hinduism", "Islam", "Christianity", 2],
["Question 25: What religion(s) is/are most common in Malaysia?", "Christianity", "Islam", "Islam", 2],
["Question 26: What religion(s) is/are most common in Japan?", "Roman Catholicism", "Christianity", "Shinto and Buddhism", 3],
["Question 27: What religion(s) is/are most common in Philippines?", "Christianity", "Christianity", "Islam", 1],
["Question 28: What religion(s) is/are most common in Morocco?", "Islam", "Christianity", "Eastern Orthodoxy", 1],
["Question 29: What religion(s) is/are most common in Brazil?", "Catholicism", "Christianity", "Roman Catholic Apostolic", 1],
["Question 30: What religion(s) is/are most common in India?", "Islam", "Catholicism", "Hinduism", 3],
["Question 31: What religion(s) is/are most common in Colombia?", "Islam", "Christianity", "Roman Catholicism", 3],
["Question 32: What religion(s) is/are most common in Peru?", "Christianity", "Roman Catholicism", "Catholicism", 2],
["Question 33: What religion(s) is/are most common in Indonesia?", "Islam", "Christianity", "Roman Catholicism", 1],
["Question 34: What religion(s) is/are most common in Ghana?", "Christianity", "Christianity", "Islam", 2],
["Question 35: What religion(s) is/are most common in United Kingdom?", "Islam", "Irreligious", "Christianity", 3],
["Question 36: What religion(s) is/are most common in Yemen?", "Islam", "Islam", "Roman Catholicism", 2],
["Question 37: What religion(s) is/are most common in South Korea?", "Irreligious", "Islam", "Roman Catholicism", 1],
["Question 38: What religion(s) is/are most common in Indonesia?", "Islam", "Islam", "Islam", 1],
["Question 39: What religion(s) is/are most common in Vietnam?", "Buddhism and Catholicism", "Islam", "Islam", 1],
["Question 40: What religion(s) is/are most common in Brazil?", "Catholicism", "Russian Orthodoxy", "Christianity", 1],
["Question 41: What religion(s) is/are most common in Mexico?", "Christianity, Islam, Indigenous Religions", "Catholicism", "Islam", 2],
["Question 42: What religion(s) is/are most common in Sudan?", "Roman Catholicism", "Islam", "Catholicism", 2],
["Question 43: What religion(s) is/are most common in Brazil?", "Islam", "Islam", "Catholicism", 3],
["Question 44: What religion(s) is/are most common in Argentina?", "Roman Catholicism", "Christianity", "Catholicism", 2],
["Question 45: What religion(s) is/are most common in United Kingdom?", "Christianity", "Islam", "Christianity", 3],
["Question 46: What religion(s) is/are most common in Mozambique?", "Roman Catholicism", "Islam", "Roman Catholicism", 3],
["Question 47: What religion(s) is/are most common in Philippines?", "Islam", "Christianity", "Islam", 2],
["Question 48: What religion(s) is/are most common in Spain?", "Christianity, Islam, Indigenous Religions", "Catholicism", "Islam", 2],
["Question 49: What religion(s) is/are most common in Nepal?", "Eastern Orthodoxy", "Christianity", "Hinduism", 3],
["Question 50: What religion(s) is/are most common in Angola?", "Christianity", "Christianity", "Roman Catholicism", 1],
["Question 51: What religion(s) is/are most common in United States?", "Roman Catholicism", "Islam", "Christianity", 3],
["Question 52: What religion(s) is/are most common in Pakistan?", "Buddhism", "Islam", "Christianity", 2],
["Question 53: What religion(s) is/are most common in Philippines?", "Christianity & Islam", "Christianity", "Christianity", 2],
["Question 54: What religion(s) is/are most common in Nigeria?", "Eastern Orthodoxy", "Christianity, Islam, Indigenous Religions", "Islam", 2],
["Question 55: What religion(s) is/are most common in Turkey?", "Islam", "Roman Catholic Apostolic", "Christianity", 1],
["Question 56: What religion(s) is/are most common in Sudan?", "Islam", "Hinduism", "Christianity", 1],
["Question 57: What religion(s) is/are most common in Tanzania?", "Roman Catholic Apostolic", "Christianity", "Islam", 2],
["Question 58: What religion(s) is/are most common in Sudan?", "Islam", "Islam", "Roman Catholicism", 2],
["Question 59: What religion(s) is/are most common in France?", "Islam", "Islam", "Catholicism", 3],
["Question 60: What religion(s) is/are most common in Myanmar?", "Buddhism", "Islam", "Islam", 1],
["Question 61: What religion(s) is/are most common in Tanzania?", "Christianity", "Christianity", "Christianity", 1],
["Question 62: What religion(s) is/are most common in Iraq?", "Islam", "Islam", "Christianity", 2],
["Question 63: What religion(s) is/are most common in Poland?", "Roman Catholicism", "Catholicism", "Roman Catholicism", 1],
["Question 64: What religion(s) is/are most common in Thailand?", "Christianity", "Buddhism", "Buddhism", 3],
["Question 65: What religion(s) is/are most common in France?", "Christianity, Islam, Indigenous Religions", "Catholicism", "Hinduism", 2],
["Question 66: What religion(s) is/are most common in Ukraine?", "Christianity", "Islam", "Eastern Orthodoxy", 3],
["Question 67: What religion(s) is/are most common in South Africa?", "Christianity", "Christianity", "Islam", 2],
["Question 68: What religion(s) is/are most common in India?", "Roman Catholicism", "Hinduism", "Buddhism", 2],
["Question 69: What religion(s) is/are most common in Vietnam?", "Irreligious", "Islam", "Buddhism and Catholicism", 3],
["Question 70: What religion(s) is/are most common in Iraq?", "Christianity", "Islam", "Christianity", 2],
["Question 71: What religion(s) is/are most common in Afghanistan?", "Islam", "Roman Catholicism", "Islam", 3],
["Question 72: What religion(s) is/are most common in Nigeria?", "Christianity, Islam, Indigenous Religions", "Christianity", "Buddhism and Catholicism", 1],
["Question 73: What religion(s) is/are most common in Bangladesh?", "Islam", "Christianity, Islam, Indigenous Religions", "Islam", 3],
["Question 74: What religion(s) is/are most common in United Kingdom?", "Islam", "Islam", "Christianity", 3],
["Question 75: What religion(s) is/are most common in DR Congo?", "Hinduism", "Roman Catholicism", "Buddhism", 2],
["Question 76: What religion(s) is/are most common in Vietnam?", "Buddhism and Catholicism", "Roman Catholicism", "Christianity", 1],
["Question 77: What religion(s) is/are most common in Uzbekistan?", "Islam", "Islam", "Islam", 3],
["Question 78: What religion(s) is/are most common in Morocco?", "Islam", "Christianity", "Islam", 3],
["Question 79: What religion(s) is/are most common in Afghanistan?", "Christianity", "Islam", "Christianity", 2],
["Question 80: What religion(s) is/are most common in Myanmar?", "Christianity", "Buddhism", "Hinduism", 2],
["Question 81: What religion(s) is/are most common in South Korea?", "Irreligious", "Christianity", "Islam", 1],
["Question 82: What religion(s) is/are most common in Germany?", "Islam", "Christianity", "Shinto and Buddhism", 2],
["Question 83: What religion(s) is/are most common in Nepal?", "Islam", "Hinduism", "Russian Orthodoxy", 2],
["Question 84: What religion(s) is/are most common in Venezuela?", "Roman Catholic Apostolic", "Islam", "Catholicism", 1],
["Question 85: What religion(s) is/are most common in Saudi Arabia?", "Islam", "Eastern Orthodoxy", "Roman Catholicism", 1],
["Question 86: What religion(s) is/are most common in Poland?", "Islam", "Roman Catholicism", "Roman Catholic Apostolic", 2],
["Question 87: What religion(s) is/are most common in Thailand?", "Buddhism", "Islam", "Islam", 1],
["Question 88: What religion(s) is/are most common in South Africa?", "Folk religions & Buddhism", "Christianity", "Buddhism and Catholicism", 2],
["Question 89: What religion(s) is/are most common in Japan?", "Islam", "Islam", "Shinto and Buddhism", 3],
["Question 90: What religion(s) is/are most common in Russia?", "Christianity", "Christianity, Islam, Indigenous Religions", "Russian Orthodoxy", 3],
["Question 91: What religion(s) is/are most common in Egypt?", "Christianity, Islam, Indigenous Religions", "Islam", "Islam", 3],
["Question 92: What religion(s) is/are most common in Japan?", "Christianity", "Shinto and Buddhism", "Shinto and Buddhism", 3],
["Question 93: What religion(s) is/are most common in Russia?", "Russian Orthodoxy", "Islam", "Islam", 1],
["Question 94: What religion(s) is/are most common in Algeria?", "Islam", "Islam", "Buddhism and Catholicism", 1],
["Question 95: What religion(s) is/are most common in Thailand?", "Christianity", "Buddhism", "Islam", 2],
["Question 96: What religion(s) is/are most common in Brazil?", "Christianity", "Islam", "Catholicism", 3],
["Question 97: What religion(s) is/are most common in Philippines?", "Christianity", "Catholicism", "Hinduism", 1],
["Question 98: What religion(s) is/are most common in Indonesia?", "Islam", "Islam", "Islam", 3],
["Question 99: What religion(s) is/are most common in Canada?", "Irreligious", "Islam", "Christianity", 3],
["Question 100: What religion(s) is/are most common in Canada?", "Christianity", "Christianity", "Islam", 1],
["Question 101: What religion(s) is/are most common in Nigeria?", "Islam", "Christianity, Islam, Indigenous Religions", "Islam", 2],
["Question 102: What religion(s) is/are most common in Yemen?", "Islam", "Roman Catholicism", "Christianity, Islam, Indigenous Religions", 1],
["Question 103: What religion(s) is/are most common in Colombia?", "Islam", "Roman Catholicism", "Roman Catholicism", 2],
["Question 104: What religion(s) is/are most common in Ethiopia?", "Christianity & Islam", "Islam", "Christianity", 1],
["Question 105: What religion(s) is/are most common in Indonesia?", "Hinduism", "Christianity", "Islam", 3],
["Question 106: What religion(s) is/are most common in Uzbekistan?", "Islam", "Christianity", "Christianity", 1],
["Question 107: What religion(s) is/are most common in South Korea?", "Roman Catholicism", "Irreligious", "Buddhism", 2],
["Question 108: What religion(s) is/are most common in Japan?", "Shinto and Buddhism", "Christianity & Islam", "Roman Catholicism", 1],
["Question 109: What religion(s) is/are most common in Brazil?", "Islam", "Catholicism", "Islam", 2],
["Question 110: What religion(s) is/are most common in Thailand?", "Buddhism", "Christianity", "Islam", 1],
["Question 111: What religion(s) is/are most common in France?", "Christianity", "Islam", "Catholicism", 3],
["Question 112: What religion(s) is/are most common in Ethiopia?", "Buddhism", "Christianity & Islam", "Islam", 2],
["Question 113: What religion(s) is/are most common in Egypt?", "Catholicism", "Buddhism and Catholicism", "Islam", 3],
["Question 114: What religion(s) is/are most common in Venezuela?", "Hinduism", "Folk religions & Buddhism", "Roman Catholic Apostolic", 3],
["Question 115: What religion(s) is/are most common in Japan?", "Christianity", "Shinto and Buddhism", "Folk religions & Buddhism", 2],
["Question 116: What religion(s) is/are most common in Brazil?", "Islam", "Islam", "Catholicism", 3],
["Question 117: What religion(s) is/are most common in Saudi Arabia?", "Islam", "Islam", "Russian Orthodoxy", 2],
["Question 118: What religion(s) is/are most common in Myanmar?", "Buddhism", "Christianity", "Roman Catholicism", 1],
["Question 119: What religion(s) is/are most common in Russia?", "Russian Orthodoxy", "Islam", "Roman Catholic Apostolic", 1],
["Question 120: What religion(s) is/are most common in Saudi Arabia?", "Islam", "Christianity", "Islam", 1],
["Question 121: What religion(s) is/are most common in DR Congo?", "Roman Catholic Apostolic", "Roman Catholicism", "Roman Catholicism", 2],
["Question 122: What religion(s) is/are most common in Mozambique?", "Islam", "Roman Catholicism", "Christianity", 2],
["Question 123: What religion(s) is/are most common in France?", "Islam", "Catholicism", "Islam", 2],
["Question 124: What religion(s) is/are most common in Morocco?", "Islam", "Roman Catholicism", "Hinduism", 1],
["Question 125: What religion(s) is/are most common in Turkey?", "Islam", "Islam", "Roman Catholicism", 2],
["Question 126: What religion(s) is/are most common in DR Congo?", "Islam", "Christianity", "Roman Catholicism", 3],
["Question 127: What religion(s) is/are most common in Iraq?", "Christianity", "Islam", "Hinduism", 2],
["Question 128: What religion(s) is/are most common in Myanmar?", "Buddhism", "Roman Catholicism", "Christianity", 1],
["Question 129: What religion(s) is/are most common in Iran?", "Islam", "Islam", "Islam", 1],
["Question 130: What religion(s) is/are most common in Bangladesh?", "Christianity", "Islam", "Hinduism", 2],
["Question 131: What religion(s) is/are most common in Sudan?", "Islam", "Roman Catholicism", "Christianity", 1],
["Question 132: What religion(s) is/are most common in Malaysia?", "Islam", "Christianity", "Folk religions & Buddhism", 1],
["Question 133: What religion(s) is/are most common in Iraq?", "Islam", "Christianity", "Catholicism", 1],
["Question 134: What religion(s) is/are most common in Tanzania?", "Folk religions & Buddhism", "Roman Catholic Apostolic", "Christianity", 3],
["Question 135: What religion(s) is/are most common in Vietnam?", "Shinto and Buddhism", "Islam", "Buddhism and Catholicism", 3],
["Question 136: What religion(s) is/are most common in Saudi Arabia?", "Catholicism", "Christianity", "Islam", 3],
["Question 137: What religion(s) is/are most common in United Kingdom?", "Christianity", "Islam", "Christianity", 1],
["Question 138: What religion(s) is/are most common in Nepal?", "Hinduism", "Christianity", "Buddhism", 1],
["Question 139: What religion(s) is/are most common in Tanzania?", "Christianity", "Islam", "Buddhism and Catholicism", 1],
["Question 140: What religion(s) is/are most common in Peru?", "Christianity", "Roman Catholicism", "Roman Catholic Apostolic", 2],
["Question 141: What religion(s) is/are most common in Morocco?", "Hinduism", "Islam", "Islam", 2],
["Question 142: What religion(s) is/are most common in Colombia?", "Islam", "Roman Catholicism", "Christianity", 2],
["Question 143: What religion(s) is/are most common in Italy?", "Hinduism", "Hinduism", "Roman Catholicism", 3],
["Question 144: What religion(s) is/are most common in Uzbekistan?", "Islam", "Roman Catholicism", "Islam", 1],
["Question 145: What religion(s) is/are most common in Turkey?", "Hinduism", "Eastern Orthodoxy", "Islam", 3],
["Question 146: What religion(s) is/are most common in South Africa?", "Catholicism", "Christianity", "Shinto and Buddhism", 2],
["Question 147: What religion(s) is/are most common in Brazil?", "Catholicism", "Buddhism", "Christianity", 1],
["Question 148: What religion(s) is/are most common in Vietnam?", "Islam", "Christianity", "Buddhism and Catholicism", 3],
["Question 149: What religion(s) is/are most common in Myanmar?", "Catholicism", "Christianity", "Buddhism", 3],
["Question 150: What religion(s) is/are most common in DR Congo?", "Christianity", "Roman Catholicism", "Irreligious", 2],
["Question 151: What religion(s) is/are most common in Morocco?", "Islam", "Christianity", "Buddhism", 1],
["Question 152: What religion(s) is/are most common in Nigeria?", "Christianity, Islam, Indigenous Religions", "Christianity", "Islam", 1],
["Question 153: What religion(s) is/are most common in Bangladesh?", "Folk religions & Buddhism", "Islam", "Islam", 2],
["Question 154: What religion(s) is/are most common in Afghanistan?", "Roman Catholicism", "Islam", "Christianity", 2],
["Question 155: What religion(s) is/are most common in Morocco?", "Islam", "Christianity", "Islam", 1],
["Question 156: What religion(s) is/are most common in Myanmar?", "Buddhism", "Russian Orthodoxy", "Eastern Orthodoxy", 1],
["Question 157: What religion(s) is/are most common in Brazil?", "Roman Catholicism", "Folk religions & Buddhism", "Catholicism", 3],
["Question 158: What religion(s) is/are most common in Nepal?", "Hinduism", "Roman Catholicism", "Roman Catholicism", 1],
["Question 159: What religion(s) is/are most common in Pakistan?", "Islam", "Hinduism", "Islam", 1],
["Question 160: What religion(s) is/are most common in Nepal?", "Hinduism", "Hinduism", "Catholicism", 1],
["Question 161: What religion(s) is/are most common in Venezuela?", "Islam", "Roman Catholic Apostolic", "Catholicism", 2],
["Question 162: What religion(s) is/are most common in Saudi Arabia?", "Catholicism", "Folk religions & Buddhism", "Islam", 3],
["Question 163: What religion(s) is/are most common in South Korea?", "Buddhism", "Islam", "Irreligious", 3],
["Question 164: What religion(s) is/are most common in Philippines?", "Christianity", "Islam", "Roman Catholicism", 1],
["Question 165: What religion(s) is/are most common in Ukraine?", "Eastern Orthodoxy", "Islam", "Islam", 1],
["Question 166: What religion(s) is/are most common in South Africa?", "Islam", "Christianity", "Buddhism", 2],
["Question 167: What religion(s) is/are most common in Nigeria?", "Christianity", "Christianity, Islam, Indigenous Religions", "Islam", 2],
["Question 168: What religion(s) is/are most common in Japan?", "Roman Catholicism", "Shinto and Buddhism", "Shinto and Buddhism", 2],
["Question 169: What religion(s) is/are most common in Ukraine?", "Christianity", "Islam", "Eastern Orthodoxy", 3],
["Question 170: What religion(s) is/are most common in Turkey?", "Russian Orthodoxy", "Christianity", "Islam", 3],
["Question 171: What religion(s) is/are most common in Myanmar?", "Islam", "Buddhism", "Islam", 2],
["Question 172: What religion(s) is/are most common in Venezuela?", "Islam", "Roman Catholic Apostolic", "Christianity", 2],
["Question 173: What religion(s) is/are most common in South Africa?", "Shinto and Buddhism", "Christianity", "Christianity", 2],
["Question 174: What religion(s) is/are most common in Vietnam?", "Islam", "Buddhism and Catholicism", "Islam", 2],
["Question 175: What religion(s) is/are most common in Iraq?", "Christianity", "Islam", "Islam", 3],
["Question 176: What religion(s) is/are most common in Angola?", "Roman Catholicism", "Christianity", "Roman Catholic Apostolic", 2],
["Question 177: What religion(s) is/are most common in Nepal?", "Hinduism", "Islam", "Christianity", 1],
["Question 178: What religion(s) is/are most common in United Kingdom?", "Christianity", "Islam", "Catholicism", 1],
["Question 179: What religion(s) is/are most common in Uzbekistan?", "Islam", "Islam", "Islam", 1],
["Question 180: What religion(s) is/are most common in Nigeria?", "Christianity, Islam, Indigenous Religions", "Islam", "Islam", 1],
["Question 181: What religion(s) is/are most common in DR Congo?", "Roman Catholicism", "Roman Catholicism", "Roman Catholicism", 1],
["Question 182: What religion(s) is/are most common in Russia?", "Roman Catholicism", "Christianity", "Russian Orthodoxy", 3],
["Question 183: What religion(s) is/are most common in Mexico?", "Christianity", "Catholicism", "Roman Catholicism", 2],
["Question 184: What religion(s) is/are most common in Thailand?", "Russian Orthodoxy", "Buddhism", "Roman Catholicism", 2],
["Question 185: What religion(s) is/are most common in Vietnam?", "Catholicism", "Buddhism and Catholicism", "Christianity", 2],
["Question 186: What religion(s) is/are most common in Myanmar?", "Roman Catholicism", "Buddhism", "Roman Catholicism", 2],
["Question 187: What religion(s) is/are most common in Bangladesh?", "Islam", "Russian Orthodoxy", "Catholicism", 1],
["Question 188: What religion(s) is/are most common in Uganda?", "Roman Catholicism", "Christianity", "Christianity", 2],
["Question 189: What religion(s) is/are most common in Iraq?", "Islam", "Christianity, Islam, Indigenous Religions", "Christianity & Islam", 1],
["Question 190: What religion(s) is/are most common in Italy?", "Roman Catholic Apostolic", "Catholicism", "Roman Catholicism", 3],
["Question 191: What religion(s) is/are most common in Sudan?", "Shinto and Buddhism", "Islam", "Roman Catholicism", 2],
["Question 192: What religion(s) is/are most common in Mozambique?", "Roman Catholicism", "Shinto and Buddhism", "Russian Orthodoxy", 1],
["Question 193: What religion(s) is/are most common in Uganda?", "Christianity", "Buddhism and Catholicism", "Christianity", 3],
["Question 194: What religion(s) is/are most common in Mexico?", "Folk religions & Buddhism", "Catholicism", "Shinto and Buddhism", 2],
["Question 195: What religion(s) is/are most common in Indonesia?", "Buddhism", "Christianity, Islam, Indigenous Religions", "Islam", 3],
["Question 196: What religion(s) is/are most common in Italy?", "Roman Catholicism", "Roman Catholicism", "Roman Catholicism", 2],
["Question 197: What religion(s) is/are most common in Malaysia?", "Christianity", "Islam", "Islam", 2],
["Question 198: What religion(s) is/are most common in Venezuela?", "Roman Catholic Apostolic", "Irreligious", "Christianity", 1],
["Question 199: What religion(s) is/are most common in Indonesia?", "Christianity", "Christianity", "Islam", 3],
["Question 200: What religion(s) is/are most common in Morocco?", "Roman Catholicism", "Christianity", "Islam", 3],
["Question 201: What religion(s) is/are most common in Mozambique?", "Roman Catholicism", "Islam", "Catholicism", 1],
["Question 202: What religion(s) is/are most common in Thailand?", "Buddhism", "Christianity", "Buddhism", 3],
["Question 203: What religion(s) is/are most common in DR Congo?", "Roman Catholicism", "Roman Catholicism", "Christianity", 1],
["Question 204: What religion(s) is/are most common in Angola?", "Christianity", "Christianity", "Roman Catholicism", 1],
["Question 205: What religion(s) is/are most common in Uzbekistan?", "Islam", "Islam", "Christianity, Islam, Indigenous Religions", 2],
["Question 206: What religion(s) is/are most common in Kenya?", "Christianity", "Roman Catholicism", "Folk religions & Buddhism", 1],
["Question 207: What religion(s) is/are most common in Myanmar?", "Hinduism", "Christianity", "Buddhism", 3],
["Question 208: What religion(s) is/are most common in Indonesia?", "Islam", "Islam", "Islam", 3],
["Question 209: What religion(s) is/are most common in Uganda?", "Islam", "Christianity", "Islam", 2],
["Question 210: What religion(s) is/are most common in Kenya?", "Christianity", "Eastern Orthodoxy", "Catholicism", 1],
["Question 211: What religion(s) is/are most common in Thailand?", "Buddhism", "Islam", "Roman Catholic Apostolic", 1],
["Question 212: What religion(s) is/are most common in Bangladesh?", "Islam", "Islam", "Christianity", 2],
["Question 213: What religion(s) is/are most common in Thailand?", "Buddhism", "Folk religions & Buddhism", "Christianity", 1],
["Question 214: What religion(s) is/are most common in Yemen?", "Buddhism", "Roman Catholicism", "Islam", 3],
["Question 215: What religion(s) is/are most common in Colombia?", "Buddhism", "Roman Catholicism", "Islam", 2],
["Question 216: What religion(s) is/are most common in Colombia?", "Christianity", "Roman Catholicism", "Roman Catholicism", 2],
["Question 217: What religion(s) is/are most common in Spain?", "Catholicism", "Christianity", "Islam", 1],
["Question 218: What religion(s) is/are most common in Malaysia?", "Roman Catholicism", "Islam", "Christianity", 2],
["Question 219: What religion(s) is/are most common in Ghana?", "Eastern Orthodoxy", "Irreligious", "Christianity", 3],
["Question 220: What religion(s) is/are most common in Poland?", "Buddhism", "Roman Catholicism", "Christianity", 2],
["Question 221: What religion(s) is/are most common in Tanzania?", "Christianity", "Eastern Orthodoxy", "Catholicism", 1],
["Question 222: What religion(s) is/are most common in Egypt?", "Islam", "Christianity", "Christianity", 1],
["Question 223: What religion(s) is/are most common in Ethiopia?", "Christianity & Islam", "Islam", "Roman Catholicism", 1],
["Question 224: What religion(s) is/are most common in Spain?", "Catholicism", "Christianity", "Islam", 1],
["Question 225: What religion(s) is/are most common in Vietnam?", "Buddhism and Catholicism", "Islam", "Islam", 1],
["Question 226: What religion(s) is/are most common in Iraq?", "Islam", "Islam", "Roman Catholicism", 2],
["Question 227: What religion(s) is/are most common in Mozambique?", "Russian Orthodoxy", "Roman Catholicism", "Roman Catholicism", 3],
["Question 228: What religion(s) is/are most common in Pakistan?", "Roman Catholicism", "Islam", "Islam", 2],
["Question 229: What religion(s) is/are most common in Mexico?", "Islam", "Roman Catholicism", "Catholicism", 3],
["Question 230: What religion(s) is/are most common in Nepal?", "Islam", "Hinduism", "Islam", 2],
["Question 231: What religion(s) is/are most common in Ukraine?", "Eastern Orthodoxy", "Islam", "Shinto and Buddhism", 1],
["Question 232: What religion(s) is/are most common in Saudi Arabia?", "Christianity", "Islam", "Islam", 3],
["Question 233: What religion(s) is/are most common in Myanmar?", "Buddhism", "Islam", "Islam", 1],
["Question 234: What religion(s) is/are most common in Argentina?", "Christianity", "Christianity", "Catholicism", 2],
["Question 235: What religion(s) is/are most common in Uganda?", "Christianity", "Islam", "Islam", 1],
["Question 236: What religion(s) is/are most common in Vietnam?", "Buddhism and Catholicism", "Christianity", "Christianity", 1],
["Question 237: What religion(s) is/are most common in Turkey?", "Christianity", "Islam", "Catholicism", 2],
["Question 238: What religion(s) is/are most common in Uganda?", "Buddhism", "Roman Catholicism", "Christianity", 3],
["Question 239: What religion(s) is/are most common in Kenya?", "Christianity", "Christianity", "Russian Orthodoxy", 2],
["Question 240: What religion(s) is/are most common in Ukraine?", "Islam", "Folk religions & Buddhism", "Eastern Orthodoxy", 3],
["Question 241: What religion(s) is/are most common in Italy?", "Islam", "Catholicism", "Roman Catholicism", 3],
["Question 242: What religion(s) is/are most common in Spain?", "Christianity", "Christianity & Islam", "Catholicism", 3],
["Question 243: What religion(s) is/are most common in United Kingdom?", "Christianity", "Christianity", "Islam", 2],
["Question 244: What religion(s) is/are most common in China?", "Christianity", "Folk religions & Buddhism", "Roman Catholicism", 2],
["Question 245: What religion(s) is/are most common in Uzbekistan?", "Islam", "Russian Orthodoxy", "Islam", 3],
["Question 246: What religion(s) is/are most common in Ethiopia?", "Islam", "Buddhism", "Christianity & Islam", 3],
["Question 247: What religion(s) is/are most common in Turkey?", "Islam", "Islam", "Islam", 1],
["Question 248: What religion(s) is/are most common in Canada?", "Buddhism", "Buddhism", "Christianity", 3],
["Question 249: What religion(s) is/are most common in Mozambique?", "Islam", "Roman Catholicism", "Christianity", 2],
["Question 250: What religion(s) is/are most common in Afghanistan?", "Islam", "Islam", "Islam", 3],
["Question 251: What religion(s) is/are most common in China?", "Christianity", "Folk religions & Buddhism", "Christianity, Islam, Indigenous Religions", 2],
["Question 252: What religion(s) is/are most common in Algeria?", "Islam", "Russian Orthodoxy", "Islam", 1],
["Question 253: What religion(s) is/are most common in Yemen?", "Buddhism", "Islam", "Christianity", 2],
["Question 254: What religion(s) is/are most common in DR Congo?", "Roman Catholicism", "Christianity", "Roman Catholicism", 1],
["Question 255: What religion(s) is/are most common in South Korea?", "Buddhism and Catholicism", "Irreligious", "Christianity", 2],
["Question 256: What religion(s) is/are most common in France?", "Catholicism", "Irreligious", "Catholicism", 3],
["Question 257: What religion(s) is/are most common in South Africa?", "Christianity", "Islam", "Christianity", 3],
["Question 258: What religion(s) is/are most common in Myanmar?", "Buddhism", "Islam", "Islam", 1],
["Question 259: What religion(s) is/are most common in Canada?", "Christianity", "Roman Catholicism", "Islam", 1],
["Question 260: What religion(s) is/are most common in Argentina?", "Christianity", "Christianity", "Christianity", 1],
["Question 261: What religion(s) is/are most common in Russia?", "Russian Orthodoxy", "Christianity", "Islam", 1],
["Question 262: What religion(s) is/are most common in Tanzania?", "Christianity", "Roman Catholicism", "Christianity", 3],
["Question 263: What religion(s) is/are most common in Yemen?", "Roman Catholicism", "Islam", "Islam", 2],
["Question 264: What religion(s) is/are most common in Canada?", "Christianity", "Buddhism", "Islam", 1],
["Question 265: What religion(s) is/are most common in Vietnam?", "Buddhism and Catholicism", "Buddhism", "Islam", 1],
["Question 266: What religion(s) is/are most common in Uzbekistan?", "Christianity & Islam", "Roman Catholicism", "Islam", 3],
["Question 267: What religion(s) is/are most common in Nepal?", "Islam", "Hinduism", "Christianity", 2],
["Question 268: What religion(s) is/are most common in United States?", "Christianity", "Hinduism", "Catholicism", 1],
["Question 269: What religion(s) is/are most common in Afghanistan?", "Islam", "Roman Catholicism", "Russian Orthodoxy", 1],
["Question 270: What religion(s) is/are most common in Ghana?", "Islam", "Christianity", "Islam", 2],
["Question 271: What religion(s) is/are most common in Uganda?", "Irreligious", "Christianity", "Islam", 2],
["Question 272: What religion(s) is/are most common in Peru?", "Roman Catholicism", "Hinduism", "Buddhism", 1],
["Question 273: What religion(s) is/are most common in Myanmar?", "Christianity", "Buddhism", "Shinto and Buddhism", 2],
["Question 274: What religion(s) is/are most common in Uganda?", "Christianity", "Christianity", "Islam", 1],
["Question 275: What religion(s) is/are most common in Sudan?", "Islam", "Islam", "Buddhism", 1],
["Question 276: What religion(s) is/are most common in Yemen?", "Islam", "Irreligious", "Islam", 3],
["Question 277: What religion(s) is/are most common in Tanzania?", "Christianity", "Roman Catholicism", "Islam", 1],
["Question 278: What religion(s) is/are most common in Sudan?", "Islam", "Islam", "Islam", 2],
["Question 279: What religion(s) is/are most common in Pakistan?", "Islam", "Christianity & Islam", "Hinduism", 1],
["Question 280: What religion(s) is/are most common in Saudi Arabia?", "Islam", "Shinto and Buddhism", "Islam", 1],
["Question 281: What religion(s) is/are most common in France?", "Christianity", "Roman Catholicism", "Catholicism", 3],
["Question 282: What religion(s) is/are most common in Nepal?", "Hinduism", "Christianity & Islam", "Catholicism", 1],
["Question 283: What religion(s) is/are most common in Mexico?", "Islam", "Catholicism", "Islam", 2],
["Question 284: What religion(s) is/are most common in Italy?", "Islam", "Islam", "Roman Catholicism", 3],
["Question 285: What religion(s) is/are most common in Thailand?", "Islam", "Buddhism", "Hinduism", 2],
["Question 286: What religion(s) is/are most common in Bangladesh?", "Christianity", "Islam", "Islam", 2],
["Question 287: What religion(s) is/are most common in Bangladesh?", "Buddhism", "Islam", "Islam", 3],
["Question 288: What religion(s) is/are most common in Morocco?", "Christianity", "Islam", "Islam", 3],
["Question 289: What religion(s) is/are most common in Philippines?", "Islam", "Christianity", "Christianity", 3],
["Question 290: What religion(s) is/are most common in Yemen?", "Islam", "Islam", "Islam", 1],
["Question 291: What religion(s) is/are most common in Sudan?", "Islam", "Islam", "Islam", 2],
["Question 292: What religion(s) is/are most common in Yemen?", "Christianity, Islam, Indigenous Religions", "Islam", "Islam", 3],
["Question 293: What religion(s) is/are most common in Mozambique?", "Christianity", "Roman Catholicism", "Christianity", 2],
["Question 294: What religion(s) is/are most common in Vietnam?", "Buddhism and Catholicism", "Islam", "Shinto and Buddhism", 1],
["Question 295: What religion(s) is/are most common in Brazil?", "Catholicism", "Islam", "Catholicism", 1],
["Question 296: What religion(s) is/are most common in South Korea?", "Christianity", "Irreligious", "Christianity", 2],
["Question 297: What religion(s) is/are most common in Pakistan?", "Islam", "Islam", "Christianity", 2],
["Question 298: What religion(s) is/are most common in United States?", "Catholicism", "Hinduism", "Christianity", 3],
["Question 299: What religion(s) is/are most common in Uganda?", "Christianity", "Buddhism", "Roman Catholicism", 1],
["Question 300: What religion(s) is/are most common in Ethiopia?", "Roman Catholicism", "Christianity", "Christianity & Islam", 3],
["Question 301: What religion(s) is/are most common in Morocco?", "Islam", "Christianity", "Christianity", 1],
["Question 302: What religion(s) is/are most common in Venezuela?", "Roman Catholicism", "Islam", "Roman Catholic Apostolic", 3],
["Question 303: What religion(s) is/are most common in Brazil?", "Roman Catholicism", "Catholicism", "Catholicism", 3],
["Question 304: What religion(s) is/are most common in South Korea?", "Irreligious", "Roman Catholicism", "Christianity & Islam", 1],
["Question 305: What religion(s) is/are most common in Philippines?", "Christianity & Islam", "Christianity", "Roman Catholic Apostolic", 2],
["Question 306: What religion(s) is/are most common in Ethiopia?", "Christianity & Islam", "Christianity", "Christianity", 1],
["Question 307: What religion(s) is/are most common in Uzbekistan?", "Islam", "Christianity", "Islam", 3],
["Question 308: What religion(s) is/are most common in South Korea?", "Buddhism", "Russian Orthodoxy", "Irreligious", 3],
["Question 309: What religion(s) is/are most common in Poland?", "Roman Catholic Apostolic", "Roman Catholicism", "Folk religions & Buddhism", 2],
["Question 310: What religion(s) is/are most common in Nigeria?", "Catholicism", "Roman Catholicism", "Christianity, Islam, Indigenous Religions", 3],
["Question 311: What religion(s) is/are most common in Kenya?", "Christianity, Islam, Indigenous Religions", "Christianity", "Roman Catholicism", 2],
["Question 312: What religion(s) is/are most common in Nepal?", "Islam", "Christianity", "Hinduism", 3],
["Question 313: What religion(s) is/are most common in Japan?", "Shinto and Buddhism", "Christianity", "Islam", 1],
["Question 314: What religion(s) is/are most common in India?", "Hinduism", "Christianity", "Christianity", 1],
["Question 315: What religion(s) is/are most common in Iran?", "Roman Catholicism", "Islam", "Christianity", 2],
["Question 316: What religion(s) is/are most common in Pakistan?", "Islam", "Islam", "Hinduism", 1],
["Question 317: What religion(s) is/are most common in Turkey?", "Islam", "Christianity", "Islam", 1],
["Question 318: What religion(s) is/are most common in Tanzania?", "Christianity", "Christianity", "Roman Catholicism", 1],
["Question 319: What religion(s) is/are most common in Ukraine?", "Islam", "Christianity", "Eastern Orthodoxy", 3],
["Question 320: What religion(s) is/are most common in Sudan?", "Roman Catholicism", "Roman Catholicism", "Islam", 3],
["Question 321: What religion(s) is/are most common in Myanmar?", "Roman Catholicism", "Irreligious", "Buddhism", 3],
["Question 322: What religion(s) is/are most common in South Korea?", "Irreligious", "Buddhism", "Christianity", 1],
["Question 323: What religion(s) is/are most common in Egypt?", "Islam", "Islam", "Catholicism", 2],
["Question 324: What religion(s) is/are most common in Nigeria?", "Christianity, Islam, Indigenous Religions", "Christianity", "Buddhism", 1],
["Question 325: What religion(s) is/are most common in Poland?", "Roman Catholicism", "Christianity", "Russian Orthodoxy", 1],
["Question 326: What religion(s) is/are most common in Algeria?", "Islam", "Christianity, Islam, Indigenous Religions", "Islam", 3],
["Question 327: What religion(s) is/are most common in France?", "Christianity", "Islam", "Catholicism", 3],
["Question 328: What religion(s) is/are most common in Bangladesh?", "Islam", "Catholicism", "Islam", 1],
["Question 329: What religion(s) is/are most common in Egypt?", "Islam", "Islam", "Christianity, Islam, Indigenous Religions", 1],
["Question 330: What religion(s) is/are most common in South Korea?", "Islam", "Christianity", "Irreligious", 3],
["Question 331: What religion(s) is/are most common in Egypt?", "Christianity", "Islam", "Islam", 3],
["Question 332: What religion(s) is/are most common in Myanmar?", "Buddhism and Catholicism", "Hinduism", "Buddhism", 3],
["Question 333: What religion(s) is/are most common in Mexico?", "Catholicism", "Christianity", "Catholicism", 3],
["Question 334: What religion(s) is/are most common in Ethiopia?", "Roman Catholicism", "Islam", "Christianity & Islam", 3],
["Question 335: What religion(s) is/are most common in Nepal?", "Islam", "Christianity", "Hinduism", 3],
["Question 336: What religion(s) is/are most common in Italy?", "Roman Catholicism", "Islam", "Roman Catholicism", 3],
["Question 337: What religion(s) is/are most common in Canada?", "Hinduism", "Christianity", "Islam", 2],
["Question 338: What religion(s) is/are most common in Kenya?", "Roman Catholicism", "Christianity", "Christianity", 3],
["Question 339: What religion(s) is/are most common in Myanmar?", "Roman Catholicism", "Islam", "Buddhism", 3],
["Question 340: What religion(s) is/are most common in Iran?", "Islam", "Islam", "Islam", 3],
["Question 341: What religion(s) is/are most common in Ghana?", "Islam", "Islam", "Christianity", 3],
["Question 342: What religion(s) is/are most common in Germany?", "Buddhism and Catholicism", "Shinto and Buddhism", "Christianity", 3],
["Question 343: What religion(s) is/are most common in Spain?", "Catholicism", "Islam", "Catholicism", 3],
["Question 344: What religion(s) is/are most common in Ukraine?", "Eastern Orthodoxy", "Buddhism", "Islam", 1],
["Question 345: What religion(s) is/are most common in Colombia?", "Christianity", "Roman Catholicism", "Christianity", 2],
["Question 346: What religion(s) is/are most common in Egypt?", "Islam", "Catholicism", "Roman Catholic Apostolic", 1],
["Question 347: What religion(s) is/are most common in Pakistan?", "Christianity", "Christianity & Islam", "Islam", 3],
["Question 348: What religion(s) is/are most common in Bangladesh?", "Islam", "Buddhism and Catholicism", "Shinto and Buddhism", 1],
["Question 349: What religion(s) is/are most common in Iraq?", "Islam", "Hinduism", "Islam", 1],
["Question 350: What religion(s) is/are most common in South Africa?", "Christianity", "Islam", "Roman Catholicism", 1],
["Question 351: What religion(s) is/are most common in Morocco?", "Catholicism", "Islam", "Folk religions & Buddhism", 2],
["Question 352: What religion(s) is/are most common in Spain?", "Catholicism", "Hinduism", "Catholicism", 3],
["Question 353: What religion(s) is/are most common in Ukraine?", "Islam", "Eastern Orthodoxy", "Catholicism", 2],
["Question 354: What religion(s) is/are most common in Poland?", "Irreligious", "Roman Catholicism", "Islam", 2],
["Question 355: What religion(s) is/are most common in Philippines?", "Christianity", "Christianity", "Christianity", 3],
["Question 356: What religion(s) is/are most common in Argentina?", "Christianity", "Christianity", "Roman Catholic Apostolic", 2],
["Question 357: What religion(s) is/are most common in Peru?", "Buddhism", "Islam", "Roman Catholicism", 3],
["Question 358: What religion(s) is/are most common in United States?", "Christianity", "Catholicism", "Islam", 1],
["Question 359: What religion(s) is/are most common in Angola?", "Roman Catholicism", "Christianity", "Christianity", 2],
["Question 360: What religion(s) is/are most common in Poland?", "Roman Catholicism", "Christianity", "Islam", 1],
["Question 361: What religion(s) is/are most common in Afghanistan?", "Islam", "Christianity", "Islam", 1],
["Question 362: What religion(s) is/are most common in Russia?", "Russian Orthodoxy", "Islam", "Christianity", 1],
["Question 363: What religion(s) is/are most common in Brazil?", "Catholicism", "Catholicism", "Christianity", 1],
["Question 364: What religion(s) is/are most common in Indonesia?", "Islam", "Christianity", "Eastern Orthodoxy", 1],
["Question 365: What religion(s) is/are most common in Peru?", "Roman Catholicism", "Catholicism", "Christianity, Islam, Indigenous Religions", 1],
["Question 366: What religion(s) is/are most common in Philippines?", "Roman Catholicism", "Islam", "Christianity", 3],
["Question 367: What religion(s) is/are most common in Angola?", "Christianity & Islam", "Christianity, Islam, Indigenous Religions", "Christianity", 3],
["Question 368: What religion(s) is/are most common in DR Congo?", "Roman Catholic Apostolic", "Christianity", "Roman Catholicism", 3],
["Question 369: What religion(s) is/are most common in Canada?", "Islam", "Roman Catholicism", "Christianity", 3],
["Question 370: What religion(s) is/are most common in Brazil?", "Roman Catholicism", "Roman Catholicism", "Catholicism", 3],
["Question 371: What religion(s) is/are most common in Japan?", "Christianity", "Christianity", "Shinto and Buddhism", 3],
["Question 372: What religion(s) is/are most common in Malaysia?", "Islam", "Christianity", "Islam", 3],
["Question 373: What religion(s) is/are most common in Germany?", "Christianity, Islam, Indigenous Religions", "Christianity", "Catholicism", 2],
["Question 374: What religion(s) is/are most common in Mozambique?", "Islam", "Islam", "Roman Catholicism", 3],
["Question 375: What religion(s) is/are most common in Poland?", "Islam", "Islam", "Roman Catholicism", 3],
["Question 376: What religion(s) is/are most common in Nigeria?", "Christianity", "Christianity, Islam, Indigenous Religions", "Islam", 2],
["Question 377: What religion(s) is/are most common in South Africa?", "Christianity", "Islam", "Hinduism", 1],
["Question 378: What religion(s) is/are most common in Ukraine?", "Christianity", "Eastern Orthodoxy", "Christianity, Islam, Indigenous Religions", 2],
["Question 379: What religion(s) is/are most common in India?", "Christianity", "Hinduism", "Folk religions & Buddhism", 2],
["Question 380: What religion(s) is/are most common in Myanmar?", "Buddhism", "Christianity", "Islam", 1],
["Question 381: What religion(s) is/are most common in Japan?", "Shinto and Buddhism", "Islam", "Islam", 1],
["Question 382: What religion(s) is/are most common in Morocco?", "Islam", "Christianity", "Shinto and Buddhism", 1],
["Question 383: What religion(s) is/are most common in Morocco?", "Christianity & Islam", "Buddhism", "Islam", 3],
["Question 384: What religion(s) is/are most common in Argentina?", "Christianity", "Christianity", "Christianity", 2],
["Question 385: What religion(s) is/are most common in South Africa?", "Christianity", "Folk religions & Buddhism", "Islam", 1],
["Question 386: What religion(s) is/are most common in Russia?", "Russian Orthodoxy", "Catholicism", "Buddhism", 1],
["Question 387: What religion(s) is/are most common in China?", "Christianity", "Islam", "Folk religions & Buddhism", 3],
["Question 388: What religion(s) is/are most common in DR Congo?", "Islam", "Roman Catholicism", "Roman Catholicism", 2],
["Question 389: What religion(s) is/are most common in Iraq?", "Roman Catholicism", "Christianity", "Islam", 3],
["Question 390: What religion(s) is/are most common in China?", "Folk religions & Buddhism", "Roman Catholic Apostolic", "Shinto and Buddhism", 1],
["Question 391: What religion(s) is/are most common in United Kingdom?", "Eastern Orthodoxy", "Christianity", "Islam", 2],
["Question 392: What religion(s) is/are most common in Sudan?", "Islam", "Roman Catholicism", "Islam", 1],
["Question 393: What religion(s) is/are most common in Spain?", "Catholicism", "Christianity", "Roman Catholicism", 1],
["Question 394: What religion(s) is/are most common in Angola?", "Islam", "Christianity", "Buddhism and Catholicism", 2],
["Question 395: What religion(s) is/are most common in Germany?", "Christianity", "Islam", "Christianity", 3],
["Question 396: What religion(s) is/are most common in India?", "Christianity", "Hinduism", "Hinduism", 2],
["Question 397: What religion(s) is/are most common in South Korea?", "Christianity", "Christianity", "Irreligious", 3],
["Question 398: What religion(s) is/are most common in Vietnam?", "Roman Catholicism", "Islam", "Buddhism and Catholicism", 3],
["Question 399: What religion(s) is/are most common in DR Congo?", "Roman Catholicism", "Christianity", "Islam", 1],
["Question 400: What religion(s) is/are most common in Sudan?", "Roman Catholicism", "Irreligious", "Islam", 3]];
let questionID = 1;
    
let title = document.getElementById('question')
let but1 = document.getElementById('but1');
let but2 = document.getElementById('but2');
let but3 = document.getElementById('but3');
let correct = document.getElementById('correct');
let incorrect = document.getElementById('incorrect');

//check(-1);
console.log(questions[0][0]);
correct.classList.add('hide');
incorrect.classList.add('hide');

title.textContent = questions[questionID][0];
but1.textContent = questions[questionID][1];
but2.textContent = questions[questionID][2];
but3.textContent = questions[questionID][3];

but1.addEventListener('click', ()=> {
    check('1')
})
but2.addEventListener('click', ()=> {
    check('2')
})
but3.addEventListener('click', ()=> {
    check('3')
})

function check(string) {
    if(questions[questionID][4] == string)
    {
        correct.classList.remove('hide');
        incorrect.classList.add('hide');
    }
    else {
        correct.classList.add('hide');
        incorrect.classList.remove('hide');

    }

    questionID = Math.floor(Math.random() * questions.length);
    title.textContent = questions[questionID][0];
    but1.textContent = questions[questionID][1];
    but2.textContent = questions[questionID][2];
    but3.textContent = questions[questionID][3];

}